# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
weight = 1

# ------------------------------------------------------------
# French language
# ------------------------------------------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2